"""
Simulate sample means of Bernoulli-distributed random variables.

The sample means are generated by averaging a specified number of Bernoulli trials, 
where each trial has a given probability of success. The generated sample means are 
saved to a file for further analysis.
"""

import argparse
import numpy as np
from pathlib import Path

# Configuration parameters
OUTPUT_PATH = Path("./../data/")

def generate_sample_means(num_samples: int, sample_size: int, probability: float, rng_seed: int) -> np.ndarray:
    """
    Generate sample means of Bernoulli-distributed random variables.

    args:
        num_samples: number of sample means to generate.
        sample_size: number of Bernoulli trials averaged per sample mean.
        probability: success probability of each Bernoulli trial.
        rng_seed: seed for the random number generator.
    
    returns:
        array of sample means
    """
    
    rng = np.random.default_rng(rng_seed)
    sample_means = np.empty(num_samples)
    for i in range(num_samples):
        sample = rng.binomial(1, probability, size=sample_size)
        sample_means[i] = np.mean(sample)
    return sample_means

def main():
    parser = argparse.ArgumentParser(description="generate and save bernoulli sample means.")
    parser.add_argument("--num_samples", type=int, default=100000, help="number of sample means to generate.")
    parser.add_argument("--sample_size", type=int, default=100, help="size of each sample.")
    parser.add_argument("--probability", type=float, default=0.2, help="probability of success for bernoulli distribution.")
    parser.add_argument("--rng_seed", type=int, default=0, help="seed for random number generator.")

    args = parser.parse_args()

    # generate sample means
    sample_means = generate_sample_means(args.num_samples, args.sample_size, args.probability, args.rng_seed)

    # save sample means to file
    file_name = f"bernoulli_mean_unbiased_p{args.probability:.4f}_size{args.sample_size}_seed{args.rng_seed}_.dat"
    header = " y (bernoulli sample means)"
    np.savetxt(OUTPUT_PATH / file_name, sample_means, header=header)

if __name__ == "__main__":
    main()
